(add-to-list 'load-path "~/.emacs.d/lisp")
(add-to-list 'load-path "~/.emacs.d/lsp")
(add-to-list 'load-path "~/.emacs.d/dap")

(require 'init-basic)
(require 'init-package)
(require 'init-evil)
(require 'init-edit)
(require 'init-completion)
(require 'init-dired)
(require 'init-window)
(require 'init-eshell)
(require 'init-project)
(require 'init-lsp)
(require 'init-dap)
(require 'cpp)
(require 'init-ui)
